@startuml
    actor Utilisateur
    participant Alfred

    Utilisateur->Alfred: demanderDernierConseil()
    activate Alfred
    Alfred->Alfred: fetchConseil()
    activate Alfred
    Alfred-->Alfred: dernierConseil
    deactivate Alfred
    Alfred-->Utilisateur: dernierConseil
    Alfred-->Utilisateur: void
    deactivate Alfred
@enduml