@startuml
    actor Utilisateur
    participant Int as ":Interface"
    participant Serv as ":ConseilService"
    participant Repo as ":ConseilRepository"
    database DB

    Utilisateur->>Int: Appuyer sur le bouton dernier conseil
    activate Int
    Int->Serv: recupererConseil()
    activate Serv
    Serv->Repo: findDernierConseil()
    activate Repo
    Repo->>DB: *requête sql*
    activate DB
    Repo<--DB: dernier conseil
    deactivate DB
    Serv<--Repo: dernierConseil
    deactivate Repo
    Int<--Serv: dernierConseil
    deactivate Serv
    Utilisateur<--Int: affichage du dernier conseil
    deactivate Int
@enduml